### ISSUE TITLE
Tetra and the future... it's in good hands.

### ISSUE THREAD

**Issue by samwillis** [tetra-framework/tetra#49]
Hey everyone 👋

Life got busy and I sadly didn't have time to work on this. I still very much believe in the concept, Django is crying out for a great full stack component framework.

I'm so thankful to @nerdoc for asking to pick up where I left it, I've added him as a collaborator to the repo.

I'm going to see if I can answer questions and offer guidance as he takes it forward.

**Comment by nerdoc** [comment]
I think I can close this by now. WIP. :smile:
