### ISSUE TITLE
This error showing when I run server Django 

### ISSUE THREAD

**Issue by AbdulkareemSasah** [tetra-framework/tetra#65]
Reverse for 'tetra_public_component_method' not found. 'tetra_public_component_method' 
is not a valid view function or pattern name.

**Comment by nerdoc** [comment]
Could you add some more information - what exactly is needed to reproduce this error? What did you do?
Can you add an example? Which version of tetra, django?
I suppose yo uran `manage.py runserver`.

Please, we all dedicate much time here, take three minutes to make a proper bug report so we can help.

**Comment by nerdoc** [comment]
Hello @AbdulkareemSasah, are you still suffering from this problem? Can I close this issue?

**Comment by nerdoc** [comment]
What I can imagine: you didn't add the tetra urlpatterns to your application, see the [Installation](https://tetra.readthedocs.io/en/stable/install/) chapter in the docs.
