### ISSUE TITLE
Implement component-as-directory approach

### ISSUE THREAD

**Issue by nerdoc** [tetra-framework/tetra#76]
See [discussion](https://github.com/tetra-framework/tetra/discussions/75) for that.

Things to implement:

* [x] auto-load components from "components" directories
* [x] use "default" library as standard
* [x] find a way abstract components can be defined without being loaded
* [x] include and bundle js/css files, like in the InlineTemplate approach

**Comment by gsxdsm** [comment]
Awesome I need to update the reload code to also handle js and css

**Comment by gsxdsm** [comment]
Added support for js and css files, including autoreload and build

https://github.com/tetra-framework/tetra/pull/79

**Comment by gsxdsm** [comment]
For "use "default" library as standard" - can you tell me more about what you were thinking here?

**Comment by nerdoc** [comment]
When writing `{℅ @ mylib.SomeComponent / %}`, tetra makes a few assumptions when resolving the component name. It tries to interpret mylib as django app, and if it exists, searches for a *default* library that contains a *SomeComponent* component. If not, it interprets "mylib" as library name and tries to find a library named "mylib" int the "current" app (containing the component).
This is working with inline components, but IMHO not yet with dies.

I would say that one has to define a library directory in any case (no components directly in <app>/components/) - so the resolving must be extended for directories too. Should be an easy task. If you are motivated @gsxdsm - else I'll do it next week.

**Comment by gsxdsm** [comment]
Thanks for explaining. That makes sense. I should be able to get to it tonight.

**Comment by nerdoc** [comment]
I merged your PR into main, but recognized (too late) that tests are failing now. `_get_component_file_path_with_extension()` raises an error, as the `importlib.import_module()` seems to do different things when importing a package or a file.

**Comment by gsxdsm** [comment]
Perfect this sounds good to me. Sorry about the failing tests will make sure to avoid that in the future. But your approach here sounds solid to me

**Comment by nerdoc** [comment]
according to the current code, the default library is used as standard. This should be true for the component-as-dir code as well. This should be tested in a better way than today, as during the tests it is not possible to  determine the current app. I have to look into this someday. But in read-world-scenarios it should work, especially for dir-based components

**Comment by nerdoc** [comment]
fixed by 23cecd545afe6a09293e19cf65fc66b3b4eac3ad
